units: Imperial

simple:
  template: "{weather_icon} {temperature | round}{temperature_unit} | Wind {wind_speed | round}{wind_speed_unit} | Precip {precipitation_chance}%"

waybar:
  text: "<span class='weather-icon'>{weather_icon}</span>  {temperature | round}{temperature_unit} | ğŸ’§ {precipitation_chance}%"
  hot_temperature: 81
  cold_temperature: 50
