units: Imperial

simple:
  template: "{weather_icon} {temperature | round}{temperature_unit} | Wind {wind_speed | round}{wind_speed_unit} | Precip {precipitation_chance}%"

waybar:
  text: "{weather_icon}  {temperature | round}{temperature_unit} | Óç± {precipitation_chance}%"
  hot_temperature: 30
  cold_temperature: 0
