[language-server.typos]
command = "typos-lsp"

[language-server.typos.config]
diagnosticSeverity = "Hint"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "typos"]

[[language]]
name = "json"
auto-format = true
language-servers = ["vscode-json-languageserver", "typos"]

[[language]]
name = "jsonc"
auto-format = true
language-servers = ["vscode-json-languageserver", "typos"]

[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server", "typos"]
file-types = [
  { glob = "**/*.lua.tmpl" }
]

[[language]]
name = "markdown"
language-servers = ["marksman", "typos"]

[[language]]
name = "toml"
roots = ["."]
language-servers = ["taplo", "typos"]

[[language]]
name = "bash"
scope = "source.sh"
file-types = [
  { glob = "**/*.sh.tmpl" },
  { glob = "**/*.bash.tmpl" },
]
shebangs = ["sh", "bash"]
language-servers = ["bash-language-server", "typos"]
