[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.haper-ls]
userDictPath = "~/.config/harper/dictionary.txt"

[language-server.harper-ls.config.harper-ls.linters]
SentenceCapitalization = false

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "harper-ls"]

[[language]]
name = "json"
auto-format = true
language-servers = ["vscode-json-languageserver", "harper-ls"]

[[language]]
name = "jsonc"
auto-format = true
language-servers = ["vscode-json-languageserver", "harper-ls"]

[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server", "harper-ls"]
file-types = [
  { glob = "**/*.lua.tmpl" }
]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "toml"
roots = ["."]
language-servers = ["taplo", "harper-ls"]

[[language]]
name = "bash"
scope = "source.sh"
file-types = [
  { glob = "**/*.sh.tmpl" },
  { glob = "**/*.bash.tmpl" },
]
shebangs = ["sh", "bash"]
language-servers = ["bash-language-server", "harper-ls"]
