prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#EAEAF2"     # base.text
      secondary: "#8A86A0"   # base.text-muted  
      inverted: "#16161E"    # base.background
      faint: "#8A86A0"       # base.comment
      warning: "#FFD300"     # semantics.warning
      success: "#00FF9C"     # semantics.success
    background:
      selected: "#2A2A33"    # ui.selection
    border:
      primary: "#CA0174"     # ui.border
      secondary: "#1F1F28"   # base.surface-1
      faint: "#21222C"       # base.surface-3
    prs:
      merged: "#FF00FF"      # accents.tertiary
      closed: "#FF003C"      # semantics.error
      open: "#00F0FF"        # accents.primary
      draft: "#8A86A0"       # base.comment
    issues:
      closed: "#FF003C"      # semantics.error
      open: "#00F0FF"        # accents.primary
    state:
      failure: "#FF003C"     # semantics.error
      pending: "#FFD300"     # semantics.warning
      success: "#00FF9C"     # semantics.success
      neutral: "#009CFF"     # semantics.info
    repo:
      private: "#FF00FF"     # accents.quaternary
      fork: "#CA0174"        # accents.secondary
      source: "#00FFFF"      # semantics.link
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
