start-at-login = true

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.bottom = 5
outer.left = 5
outer.right = 5
outer.top = 5

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[mode.main.binding]
cmd-alt-ctrl-shift-x = 'exec-and-forget open -a "System Settings"'
cmd-alt-ctrl-shift-e = 'exec-and-forget open -a "Finder"'
cmd-alt-ctrl-shift-enter = 'exec-and-forget open -na wezterm'
cmd-alt-ctrl-shift-q = 'close'

cmd-alt-ctrl-shift-semicolon = 'layout floating tiling'
cmd-alt-ctrl-shift-f = 'fullscreen'
cmd-alt-ctrl-shift-v = 'layout tiles vertical horizontal'
cmd-alt-ctrl-shift-m = 'mode move'
cmd-alt-ctrl-shift-r = 'mode resize'
cmd-alt-ctrl-shift-backslash = 'mode service'

# Focus movement
cmd-alt-ctrl-shift-h = 'focus left'
cmd-alt-ctrl-shift-j = 'focus down'
cmd-alt-ctrl-shift-k = 'focus up'
cmd-alt-ctrl-shift-l = 'focus right'

# Workspaces
cmd-alt-ctrl-shift-1 = 'workspace 1'
cmd-alt-ctrl-shift-2 = 'workspace 2'
cmd-alt-ctrl-shift-3 = 'workspace 3'
cmd-alt-ctrl-shift-4 = 'workspace 4'
cmd-alt-ctrl-shift-5 = 'workspace 5'
cmd-alt-ctrl-shift-6 = 'workspace 6'
cmd-alt-ctrl-shift-7 = 'workspace 7'
cmd-alt-ctrl-shift-8 = 'workspace 8'
cmd-alt-ctrl-shift-9 = 'workspace 9'
cmd-alt-ctrl-shift-0 = 'workspace 10'

## Move to workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

## Workspace navigation
cmd-alt-ctrl-shift-period = 'workspace --wrap-around next'
cmd-alt-ctrl-shift-comma = 'workspace --wrap-around prev'

[mode.move.binding]
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'

esc = 'mode main'

[mode.resize.binding]
h = 'resize smart -50'
j = 'resize smart -50'
k = 'resize smart +50'
l = 'resize smart +50'

esc = 'mode main'

[mode.service.binding]
r = ['reload-config', 'mode main']
e = ['flatten-workspace-tree', 'mode main']
b = ['balance-sizes', 'mode main']

esc = 'mode main'
